name        : bash
version     : 4.3.39
release     : 22
source      :
    - https://ftp.gnu.org/gnu/bash/bash-4.3.30.tar.gz : 317881019bbf2262fb814b7dd8e40632d13c3608d2f237800a8828fbb8a640dd
license     :
    - GPL-3.0
summary     : bash (sh-compatible shell)
description : |
    bash (sh-compatible shell) The GNU Bourne-Again SHell.  Bash is a sh-compatible command interpreter that executes commands read from the standard input or from a file.  Bash also incorporates useful features from the Korn and C shells (ksh and csh).  Bash is ultimately intended to be a conformant implementation of the IEEE Posix Shell and Tools specification (IEEE Working Group 1003.2). Bash must be present for the system to boot properly.
setup      : |
    PATCH_START=031
    PATCH_END=039
    for i in $(seq -f "%03g" $PATCH_START $PATCH_END)
    do
        zcat $pkgfiles/bash43-$i.gz | %patch -p0
    done
        
    %configure --with-curses \
               --enable-history \
               --with-installed-readline \
               --docdir=/usr/share/doc/bash
build      : |
    %make
install    : |
    %make_install
    install -d $installdir/bin
    mv $installdir/usr/bin/bash $installdir/bin/bash
    # bash as system shell
    ln -sfv /bin/bash $installdir/bin/sh
    
    install -D -d $installdir/etc/profile.d
    install -m 0644 $pkgfiles/profile/50-*.sh $installdir/etc/profile.d/.
    install -m 0644 $pkgfiles/profile/profile $installdir/etc/profile
