name       : bash
version    : 5.1.8
release    : 59
source     :
    - https://ftp.gnu.org/gnu/bash/bash-5.1.tar.gz : cc012bc860406dcf42f64431bcd3d2fa7560c02915a601aba9cd597a39329baa
license    :
    - GPL-3.0-or-later
homepage   : https://www.gnu.org/software/bash
component  :
    - system.base
    - recovery : system.boot
summary    :
    - bash (sh-compatible shell)
    - recovery : Specialised bash build for the initramfs
description: |
    bash (sh-compatible shell) The GNU Bourne-Again SHell.  Bash is a sh-compatible command interpreter that executes commands read from the standard input or from a file.  Bash also incorporates useful features from the Korn and C shells (ksh and csh).  Bash is ultimately intended to be a conformant implementation of the IEEE Posix Shell and Tools specification (IEEE Working Group 1003.2). Bash must be present for the system to boot properly.
optimize   :
    - size
    - lto
builddeps  :
    - musl-devel
patterns   :
    - recovery : /bin/bash.recovery
rundeps    :
    - recovery : bash # We want the main bash files.
setup      : |
    %apply_patches

    mkdir glibc-build && mkdir musl-build

    # Configure the musl build
    pushd musl-build

    # Just make the .a files neatly accessible to musl
    mkdir farm
    ln -sv %libdir%/libncursesw.a farm/.
    ln -sv libncursesw.a farm/libncurses.a
    ln -sv libncursesw.a farm/libcurses.a

    OLDCC="$CC"
    export CC="musl-gcc"
    ../configure %CONFOPTS% \
                 --with-curses \
                 --enable-history \
                 --enable-static-link \
                 --disable-rpath \
                 --without-bash-malloc \
                 --disable-nls \
                 --docdir=/usr/share/doc/bash \
                 CFLAGS="$CFLAGS -static -L`pwd`/farm"
    popd
    export CC="$OLDCC"

    pushd glibc-build
    ../configure %CONFOPTS% \
                 --with-curses \
                 --enable-history \
                 --enable-static-link \
                 --disable-rpath \
                 --without-bash-malloc \
                 --docdir=/usr/share/doc/bash
build      : |
    OLDCC="$CC"
    export CC="musl-gcc"
    %make -C musl-build
    export CC="$OLDCC"
    %make -C glibc-build
install    : |
    install -d $installdir/bin

    # musl install, rename binary
    OLDCC="$CC"
    export CC="musl-gcc"
    %make_install -C musl-build
    mv $installdir/usr/bin/bash $installdir/bin/bash.recovery

    # Standard glibc build, preserve binary name
    export CC="$OLDCC"
    %make_install -C glibc-build

    mv $installdir/usr/bin/bash $installdir/bin/bash
    # bash as system shell
    ln -sfv /bin/bash $installdir/bin/sh

    install -D -d $installdir/usr/share/defaults/etc/profile.d
    install -m 0644 $pkgfiles/profile/*.sh $installdir/usr/share/defaults/etc/profile.d/.
    install -m 0644 $pkgfiles/profile/profile $installdir/usr/share/defaults/etc/profile

    # sad symlink is sad, this is our own fault due to default .bashrc
    mkdir $installdir/etc
    ln -sv /usr/share/defaults/etc/profile $installdir/etc/profile
