name       : bash
version    : 4.3.042
release    : 35
source     :
    - https://ftp.gnu.org/gnu/bash/bash-4.3.30.tar.gz : 317881019bbf2262fb814b7dd8e40632d13c3608d2f237800a8828fbb8a640dd
license    :
    - GPL-3.0
component  : system.base
summary    : bash (sh-compatible shell)
description: |
    bash (sh-compatible shell) The GNU Bourne-Again SHell.  Bash is a sh-compatible command interpreter that executes commands read from the standard input or from a file.  Bash also incorporates useful features from the Korn and C shells (ksh and csh).  Bash is ultimately intended to be a conformant implementation of the IEEE Posix Shell and Tools specification (IEEE Working Group 1003.2). Bash must be present for the system to boot properly.
optimize   : size
setup      : |
    PATCH_START=031
    PATCH_END=042
    for i in $(seq -f "%03g" $PATCH_START $PATCH_END)
    do
        zcat $pkgfiles/bash43-$i.gz | %patch -p0
    done

    # stateless
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-profile-by-default.patch
    %configure --with-curses \
               --enable-history \
               --with-installed-readline \
               --docdir=/usr/share/doc/bash
build      : |
    %make
install    : |
    %make_install
    install -d $installdir/bin
    mv $installdir/usr/bin/bash $installdir/bin/bash
    # bash as system shell
    ln -sfv /bin/bash $installdir/bin/sh

    install -D -d $installdir/usr/share/defaults/etc/profile.d
    install -m 0644 $pkgfiles/profile/50-*.sh $installdir/usr/share/defaults/etc/profile.d/.
    install -m 0644 $pkgfiles/profile/profile $installdir/usr/share/defaults/etc/profile

    # sad symlink is sad, this is our own fault due to default .bashrc
    mkdir $installdir/etc
    ln -sv /usr/share/defaults/etc/profile $installdir/etc/profile
